vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/visites
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
